// import {Navbar, Footer} from '@/components/common'
import { Navbar } from '@/components/common'
import { Banner, Courses, MasterCoding } from '@/components/landing-page'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Code Greeks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{
        backgroundImage: "url('../../../assets/banner-bg.png')",
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'cover',
        backgroundPosition: 'center' }}>    
        <Navbar />     
        <Banner />
      </main>
      
      <MasterCoding />
      <Courses />




    </>
  )
}
